### ISSUE TITLE
Cannot scan with a wwan0 IPv6 address.

### ISSUE THREAD

**Issue by Infiltra** [sfan5/fi6s#5]
Hi,
I have a Quectel modem which I have connectivity by using mmcli. Then whatever IP I've got I am assigning the same IP to the wwan0 interface of my laptop.  The current wwan0 ip on my interface looks like this. 

` wwan0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/none 
    inet6 2409:40f2:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::4574:8ba5:ac95:dae7/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever`
When I launch fi6s it simply returns saying 
`neverville@thillai:~/fi6s$ ./fi6s -p 80 2409:40f2::/129
Using default interface 'wwan0'
Warning: Your machine does not seem to have any IPv6 connectivity
Failed to parse target specification.`

May I know what has happened here?

**Comment by sfan5** [comment]
First off `/129` is not a valid netmask, IPv6 "only" has 128 bits.

The "Your machine does not seem to have any IPv6 connectivity" message happens when fi6s could not find a default route.
You can try something l like `curl v6.ipinfo.io` first to verify that IPv6 is working at all.
If that *works* please provide the output of `ip -6 r`.
